name: checklist_app
description: Aplicativo de Checklist com Assinatura e PDF

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  signature: ^5.4.0
  pdf: ^3.10.0
  printing: ^5.9.0
  path_provider: ^2.0.15
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
